# Generated by Django 4.0.6 on 2022-07-11 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watch_alter_review_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchlist',
            new_name='watch',
        ),
        migrations.AlterField(
            model_name='watch',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='watchlist.streamplatform'),
        ),
    ]
