# Generated by Django 4.0.6 on 2022-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='ratings_number',
            field=models.IntegerField(default=0),
        ),
    ]
